version: "2"

services:
  db:
    image: cassandra
    ports: 
     - 7000:7000
     - 7001:7001
     - 7199:7199
     - 9042:9042
     - 9160:9160
  api:
    build: "./api"
    ports:
      - "8000:8000"
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src/:/src/src"
